### ISSUE TITLE
Mirror Mangafox MangaFox.js not working anymore

### ISSUE THREAD

**Issue by typhoe** [AllMangasReader-dev/mirrors#25]
Hi,

as reported in various places, MangaFox mirror is not working anymore.
http://community.allmangasreader.com/comments.php?type=2&id=191
http://www.allmangasreader.com/forum/viewtopic.php?f=3&t=4760

When you try to display the whole chapter for any manga, all you get is thumbnails of the cover in place of each images.

Regards.

**Comment by typhoe** [comment]
Well, I tried to see if I could debug the problem by myself... but to no avail... I don't really know javascript and can't even load the MangaFox.js locally.
I tried to follow the instructions but all I get is errors. 
Here's what I did:
+ copying locally the extension
+ add a copy of MangaFox.js renammed to MangaFox2.js in js/mirror/ and edid the file to change its mirrorName
+ edit mgEntry.js and changed var localMirrors = [ 'MangaFox2' ];
Then when I try to load this unpacked extension, I get error loading the various mirrors from community.allmangasreader.com/latest_v2/ and never see anything about my local copy of the mirror and even trying to edit the manifest.json file doesn't work...
So if I'm not even able to load a local test, I won't be able to debug anything at all...

Otherwise, I tried to see what Chromium sees when I try to display a Manga.
I tried with http://mangafox.me/manga/azumi/v19/c141/1.html
All my browser display is covers from the url http://h.mfcdn.net/store/manga/12852/cover.jpg?token=ac065426311a1fa0366564287183e33d&ttl=1482580800
But if I inspect the page (Ctrl+Maj+I), I see that all the right images are loaded:
1st one: http://h.mfcdn.net/store/manga/12852/19-141.0/compressed/e183012_009_019_130_copy.jpg?token=7ae243c9a7fa132f4043aeac1861c89e&ttl=1482580800
2nd one: http://h.mfcdn.net/store/manga/12852/19-141.0/compressed/e183012_009_019_131_copy.jpg?token=b5a25b10a0084cf8950733104d555449&ttl=1482580800

So something is happening wrongly when displaying, but not when grabbing the images...

That's all I'm able to see so far...

**Comment by Snipeon** [comment]
hmm..., pretty sure it has something to do with this line of code...

`                var src = $('#image').attr('src') || $("meta[property='og:image']", div).attr("content").replace(/thumbnails\/(?:mini.)?/, "compressed/");
                $(image).attr("src", src);`

Linked it for you just in case you wanna take a crack at it.
[https://github.com/AllMangasReader-dev/mirrors/blob/master/MangaFox.js#L192-L193](url)

well, I'm pretty rusty already, seeing as I have not even coded for the past three years. Have fun~

**Comment by typhoe** [comment]
Thanks @Snipeon .

That's what I also though after reading the documentation about the functions in the Mirror javascript file.

My problem is that without being able to test anything, it's kind of hard to try to change the code and see the result...

**Comment by Snipeon** [comment]
you realize you can load a custom AMR to read the mirrors off your computer/own github branch? Here's how to do it...

http://allmangasreader.com/dev.php

**Comment by typhoe** [comment]
Yes, that's the instructions I tried to follow... As stated in my first post, it doesn't seem to work.

I'm using Arch Linux and Chromium 55.

**Comment by Snipeon** [comment]
Well, in that case I'll suggest you load the mirrors off your github branch and edit from there. Removes the need to constantly reload the extension as well.

It's in these first 3 lines.
`var amrc_repository        = "https://community.allmangasreader.com/latest_v2/";
var amrc_root              = "https://community.allmangasreader.com/latest_v2/";
var amrc_repository_backup = "https://raw.github.com/AllMangasReader-dev/mirrors/master/";`

Just change
`var amrc_root              = "https://community.allmangasreader.com/latest_v2/";`
to
`var amrc_root              = "https://raw.github.com/typhoe/mirrors/tree/master";`

**Comment by typhoe** [comment]
First, thank you for taking time to try to help me!

So ok, I tried again (I already tried that I think):

cp -prv .config/chromium/Default/Extensions/nhjloagockgobfpopemejpgjjechcpfd ~/AMR-test
# Change mgEntry.js
grep "var amrc_root" ~/AMR-test/1.5.10.1_1/js/mgEntry.js
//var amrc_root              = "https://community.allmangasreader.com/latest_v2/";
var amrc_root              = "https://raw.github.com/typhoe/mirrors/tree/master/";

Then in Chromium, activate Dev Mode, and load unpacked extension (previously removed the official extension)
And at last, in the plugin, refresh "Websites implementations"

Well, when I look in Chromium Developer Tools, the file MangaFox.js appears loaded from community.allmangasreader.com/latest_v2/ and not from my github repository...

I added a comment on line 2 in the file to see if I'm loading the right one and still not see it...
https://github.com/typhoe/mirrors/blob/master/MangaFox.js#L2

If I try to also change the var amrc_repository, the extension doesn't seem to be able to load any mirror.

An other idea?

**Comment by Snipeon** [comment]
Sigh... you didn't notice I edited my previous comment did you?

> Just change
var amrc_repository = "https://community.allmangasreader.com/latest_v2/";
var amrc_root = "https://community.allmangasreader.com/latest_v2/";
var amrc_repository_backup = "https://raw.github.com/AllMangasReader-dev/mirrors/master/";

to
var amrc_repository = "https://raw.github.com/typhoe/mirrors/tree/master";
var amrc_root = "https://community.allmangasreader.com/latest_v2/";
var amrc_repository_backup = "https://raw.github.com/typhoe/mirrors/tree/master";

Edited: sorry, as said, I'm pretty rusty after all...

**Comment by typhoe** [comment]
Ok, I eventually succeed  in loading my own copy of the mirror file...

To sum it up:
1. you need the / at the end of the urls
2. github won't work whatever url you try to use... (and thus, I don't think the amrc_repository_backup is of any use at all...)
3. you need to use your own web server allowing the indexes option (to view the files in the directory)

Here are the various tries I did:

`// Original values
//var amrc_repository        = "https://community.allmangasreader.com/latest_v2/";
//var amrc_root              = "https://community.allmangasreader.com/latest_v2/";
//var amrc_repository_backup = "https://raw.github.com/AllMangasReader-dev/mirrors/master/";

// Works !!! Own web server allowing the view of the files in the directory
var amrc_repository        = "https://allmangasreader.typhoe.com/";
var amrc_root              = "https://community.allmangasreader.com/latest_v2/";
var amrc_repository_backup = "https://raw.github.com/AllMangasReader-dev/mirrors/master/";

// Uncaught TypeError: Cannot create property 'jsCode' on string '['
//var amrc_repository        = "https://raw.github.com/typhoe/mirrors/master/";
//var amrc_root              = "https://community.allmangasreader.com/latest_v2/";
//var amrc_repository_backup = "https://raw.github.com/typhoe/mirrors/master/";

// Uncaught TypeError: Cannot create property 'jsCode' on string '['
//var amrc_repository        = "https://raw.githubusercontent.com/typhoe/mirrors/master/";
//var amrc_root              = "https://community.allmangasreader.com/latest_v2/";
//var amrc_repository_backup = "https://raw.githubusercontent.com/typhoe/mirrors/master/";

// https://raw.github.com/typhoe/mirrors/masterwebsites.json not found 404 (missing /)
//var amrc_repository        = "https://raw.github.com/typhoe/mirrors/master";
//var amrc_root              = "https://community.allmangasreader.com/latest_v2/";
//var amrc_repository_backup = "https://raw.github.com/typhoe/mirrors/master";

// https://rawgit.com/typhoe/mirrors/tree/master/websites.json not found 404
//var amrc_repository        = "https://rawgit.com/typhoe/mirrors/tree/master/";
//var amrc_root              = "https://community.allmangasreader.com/latest_v2/";
//var amrc_repository_backup = "https://rawgit.com/typhoe/mirrors/tree/master/";

// https://cdn.rawgit.com/typhoe/mirrors/tree/master/websites.json not found 404
//var amrc_repository        = "https://cdn.rawgit.com/typhoe/mirrors/tree/master/";
//var amrc_root              = "https://community.allmangasreader.com/latest_v2/";
//var amrc_repository_backup = "https://cdn.rawgit.com/typhoe/mirrors/tree/master/";
`

And now, the hardest part, understanding javascript and finding the error... 

Thanks again for trying to help me @Snipeon

**Comment by typhoe** [comment]
Hi,

I have created a pull request with the solution to the problem.

Thanks again @Snipeon for your help!

Regards.
